Repository Heegu-sama/Homm3BG, pull requests merged in 2024-10, with the labels that each got.

#701 [PL] Fix in Trading
  translations/trading.tex/pl.po
Labels: 🇵🇱 Polish

#705 [DE] Translation backcover
  translations/back_cover.tex/de.po
Labels: 🇩🇪 German

#696 [DE] Translate Resources
  translations/resources.tex/de.po
Labels: 🇩🇪 German

#708 [FR] units new box
  translations/units.tex/fr.po
Labels: 🇫🇷 French

#714 [HE] back cover
  translations/back_cover.tex/he.po
Labels: 🇮🇱 Hebrew

#710 [HE] all_map_locations
  translations/all_map_locations.tex/he.po
Labels: 🇮🇱 Hebrew

#715 [HE] Fix alignment of images in all map locations
  translations/all_map_locations.tex/he.po
Labels: 🇮🇱 Hebrew

#707 [DE] Translation Trading
  translations/trading.tex/de.po
Labels: 🇩🇪 German

#704 [DE] Translation Roundstructure
  translations/round_structure.tex/de.po
Labels: 🇩🇪 German

#717 [HE] fixing 2 fuzzy transaltions
  translations/expansion_content.tex/he.po
  translations/round_structure.tex/he.po
Labels: 🇮🇱 Hebrew

#724 [ES] Split long titles into 2 lines
  metadata.tex
  translations/all_map_locations.tex/es.po
  translations/round_structure.tex/es.po
Labels: enhancement, 🇪🇸 Spanish

#706 [DE] Translation Components
  translations/assets/de/astrolog-shorter.png
  translations/components.tex/de.po
Labels: 🇩🇪 German

#731 Specify charset for po4a
  .github/workflows/po4a-check.yaml
  .github/workflows/po4a-comment-check.yaml
  .github/workflows/po4a-comment-commit.yaml
  po4a.cfg
  translations/ai_rules.tex/ai_rules.tex.pot
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/back_cover.tex/back_cover.tex.pot
  translations/combat.tex/combat.tex.pot
  translations/components.tex/components.tex.pot
  translations/credits.tex/credits.tex.pot
  translations/deckbuilding.tex/deckbuilding.tex.pot
  translations/difficulty.tex/difficulty.tex.pot
  translations/expansion_content.tex/expansion_content.tex.pot
  translations/game_modes.tex/game_modes.tex.pot
  translations/heroes.tex/heroes.tex.pot
  translations/index.tex/index.tex.pot
  translations/introduction.tex/introduction.tex.pot
  translations/map_elements.tex/map_elements.tex.pot
  translations/notes.tex/notes.tex.pot
  translations/player_turns.tex/player_turns.tex.pot
  translations/quote_page.tex/quote_page.tex.pot
  translations/resources.tex/resources.tex.pot
  translations/round_structure.tex/round_structure.tex.pot
  translations/scenario_end.tex/scenario_end.tex.pot
  translations/setup.tex/setup.tex.pot
  translations/title_page.tex/title_page.tex.pot
  translations/town.tex/town.tex.pot
  translations/trading.tex/trading.tex.pot
  translations/units.tex/units.tex.pot
Labels: bug, enhancement

#733 [HE] deckbuilding
  translations/deckbuilding.tex/he.po
Labels: 🇮🇱 Hebrew
