Repository Heegu-sama/Homm3BG, pull requests merged in 2024-12, with the labels that each got.

#764 [PL] Use correct page shorthand
  main_pl.tex
  translations/all_map_locations.tex/pl.po
  translations/expansion_content.tex/pl.po
Labels: 🇵🇱 Polish

#750 [DE] Translations Deckbuilding
  translations/deckbuilding.tex/de.po
Labels: 🇩🇪 German

#767 [DE] Translation Index, Notes
  translations/index.tex/de.po
  translations/notes.tex/de.po
Labels: 🇩🇪 German

#762 [DE] Translation AI-Rules
  sections/ai_rules.tex
  translations/ai_rules.tex/ai_rules.tex.pot
  translations/ai_rules.tex/cs.po
  translations/ai_rules.tex/de.po
  translations/ai_rules.tex/es.po
  translations/ai_rules.tex/fr.po
  translations/ai_rules.tex/he.po
  translations/ai_rules.tex/pl.po
  translations/ai_rules.tex/ru.po
  translations/ai_rules.tex/ua.po
  translations/assets/de/ai.png
Labels: 🇩🇪 German

#768 [DE] Replace english cards with german
  translations/assets/de/Knowledge.png
  translations/assets/de/artifact.png
  translations/assets/de/hero.png
  translations/assets/de/necromancy_card.png
  translations/assets/de/specialty.png
  translations/assets/de/spell.png
  translations/assets/de/unit-few.png
  translations/assets/de/unit-pack.png
  translations/deckbuilding.tex/de.po
  translations/heroes.tex/de.po
  translations/units.tex/de.po
Labels: 🇩🇪 German

#758 [DE] Translation Expansion Content
  sections/expansion_content.tex
  translations/assets/de/empowered_statistic.png
  translations/assets/de/event.png
  translations/assets/de/statistic.png
  translations/assets/de/war_machine.png
  translations/credits.tex/de.po
  translations/expansion_content.tex/cs.po
  translations/expansion_content.tex/de.po
  translations/expansion_content.tex/es.po
  translations/expansion_content.tex/expansion_content.tex.pot
  translations/expansion_content.tex/fr.po
  translations/expansion_content.tex/he.po
  translations/expansion_content.tex/pl.po
  translations/expansion_content.tex/ru.po
  translations/expansion_content.tex/ua.po
Labels: 🇩🇪 German

#772 [DE] Graphical fixes
  README.md
  translations/all_map_locations.tex/de.po
  translations/heroes.tex/de.po
Labels: 🇩🇪 German

#763 [RU] various stylistic fixes
  main_ru.tex
  tools/build.sh
  translations/ai_rules.tex/ru.po
  translations/all_map_locations.tex/ru.po
  translations/combat.tex/ru.po
  translations/components.tex/ru.po
  translations/deckbuilding.tex/ru.po
  translations/expansion_content.tex/ru.po
  translations/heroes.tex/ru.po
  translations/introduction.tex/ru.po
  translations/map_elements.tex/ru.po
  translations/player_turns.tex/ru.po
  translations/scenario_end.tex/ru.po
  translations/setup.tex/ru.po
  translations/town.tex/ru.po
  translations/trading.tex/ru.po
  translations/units.tex/ru.po
Labels: 🇷🇺 Russian

#775 [PL] Fix translation error.
  translations/heroes.tex/pl.po
Labels: 🇵🇱 Polish
