Repository Heegu-sama/Homm3BG, pull requests merged in 2024-09, with the labels that each got.

#677 [CZ] translation fix
  translations/introduction.tex/cs.po
Labels: 🇨🇿 Czech

#646 Ru/fix index
  README.md
  translations/ai_rules.tex/ru.po
  translations/all_map_locations.tex/ru.po
  translations/combat.tex/ru.po
  translations/components.tex/ru.po
  translations/credits.tex/ru.po
  translations/deckbuilding.tex/ru.po
  translations/difficulty.tex/ru.po
  translations/expansion_content.tex/ru.po
  translations/game_modes.tex/ru.po
  translations/heroes.tex/ru.po
  translations/map_elements.tex/ru.po
  translations/other_rules.tex/ru.po
  translations/player_turns.tex/ru.po
  translations/resources.tex/ru.po
  translations/round_structure.tex/ru.po
  translations/scenario_end.tex/ru.po
  translations/setup.tex/ru.po
  translations/town.tex/ru.po
  translations/trading.tex/ru.po
  translations/units.tex/ru.po
Labels: 🇷🇺 Russian

#686 [HE] difficulty
  translations/difficulty.tex/he.po
Labels: 🇮🇱 Hebrew

#683 Spanish corrections
  translations/ai_rules.tex/es.po
  translations/all_map_locations.tex/es.po
  translations/combat.tex/es.po
  translations/components.tex/es.po
  translations/deckbuilding.tex/es.po
  translations/difficulty.tex/es.po
  translations/expansion_content.tex/es.po
  translations/heroes.tex/es.po
  translations/introduction.tex/es.po
  translations/map_elements.tex/es.po
  translations/player_turns.tex/es.po
  translations/round_structure.tex/es.po
  translations/scenario_end.tex/es.po
  translations/setup.tex/es.po
  translations/town.tex/es.po
  translations/trading.tex/es.po
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#666 [FR] unfuzzy combat section
  translations/combat.tex/fr.po
Labels: 🇫🇷 French

#695 Make readme FOSS-project-like
  .github/CODEOWNERS
  .github/workflows/build-and-publish-rule-book.yaml
  .github/workflows/po4a-check.yaml
  .github/workflows/po4a-comment-check.yaml
  .github/workflows/po4a-comment-commit.yaml
  README.md
  tools/build.sh
  tools/release.sh
Labels: documentation, enhancement

#679 Fr/unfuzzy 1.3
  translations/ai_rules.tex/fr.po
  translations/deckbuilding.tex/fr.po
  translations/expansion_content.tex/fr.po
  translations/round_structure.tex/fr.po
Labels: 🇫🇷 French
