Repository Heegu-sama/Homm3BG, pull requests merged in 2024-08, with the labels that each got.

#658 Make attack die wording consistent
  sections/combat.tex
  sections/difficulty.tex
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/cs.po
  translations/combat.tex/de.po
  translations/combat.tex/es.po
  translations/combat.tex/fr.po
  translations/combat.tex/he.po
  translations/combat.tex/pl.po
  translations/combat.tex/ru.po
  translations/combat.tex/ua.po
  translations/difficulty.tex/cs.po
  translations/difficulty.tex/de.po
  translations/difficulty.tex/difficulty.tex.pot
  translations/difficulty.tex/es.po
  translations/difficulty.tex/fr.po
  translations/difficulty.tex/he.po
  translations/difficulty.tex/pl.po
  translations/difficulty.tex/ru.po
  translations/difficulty.tex/ua.po
Labels: changes text

#657 [PL] Unfuzzy AI + Expansion Content
  translations/ai_rules.tex/pl.po
  translations/expansion_content.tex/pl.po
Labels: 🇵🇱 Polish

#659 [ES] Unfuzzy all es.po, fixed a few errors, fixed/capitalized several terms.
  translations/ai_rules.tex/es.po
  translations/all_map_locations.tex/es.po
  translations/combat.tex/es.po
  translations/components.tex/es.po
  translations/deckbuilding.tex/es.po
  translations/difficulty.tex/es.po
  translations/expansion_content.tex/es.po
  translations/heroes.tex/es.po
  translations/map_elements.tex/es.po
  translations/player_turns.tex/es.po
  translations/resources.tex/es.po
  translations/round_structure.tex/es.po
  translations/scenario_end.tex/es.po
  translations/setup.tex/es.po
  translations/town.tex/es.po
  translations/trading.tex/es.po
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#661 [PL] Adjust index
  index_style.ist
  translations/ai_rules.tex/pl.po
  translations/all_map_locations.tex/pl.po
  translations/combat.tex/pl.po
  translations/deckbuilding.tex/pl.po
  translations/expansion_content.tex/pl.po
  translations/heroes.tex/pl.po
  translations/player_turns.tex/pl.po
  translations/resources.tex/pl.po
  translations/round_structure.tex/pl.po
  translations/town.tex/pl.po
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#665 Translated inability to summon neutral units clarification.
  translations/expansion_content.tex/es.po
Labels: 🇪🇸 Spanish

#653 [HE] ai
  translations/ai_rules.tex/he.po
Labels: 🇮🇱 Hebrew

#664 Reword and move instant defeat option
  sections/combat.tex
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/cs.po
  translations/combat.tex/de.po
  translations/combat.tex/es.po
  translations/combat.tex/fr.po
  translations/combat.tex/he.po
  translations/combat.tex/pl.po
  translations/combat.tex/ru.po
  translations/combat.tex/ua.po
Labels: changes text

#670 [ES] Unfuzzy combat from PR 664
  translations/combat.tex/es.po
Labels: 🇪🇸 Spanish
