Repository Heegu-sama/Homm3BG, pull requests merged in 2024-04, with the labels that each got.

#153 [PL] Game Modes
  translations/game_modes.tex/pl.po
Labels: 🇵🇱 Polish

#155 Add initial Polish translation for Credits
  sections/credits.tex
  translations/credits.tex/credits.tex.pot
  translations/credits.tex/pl.po
Labels: 🇵🇱 Polish

#152 translate chapter round structure to polish language
  translations/round_structure.tex/pl.po
Labels: 🇵🇱 Polish

#160 Fix Polish title page
  assets/layout/translated_cover_subtitles/pl.png
  translations/assets/pl/cover_subtitle.png
  translations/title_page.tex/pl.po
Labels: 🇵🇱 Polish

#161 [PL] Setup translation
  translations/setup.tex/pl.po
Labels: 🇵🇱 Polish

#177 Push built pdf to an external repo
  .github/workflows/build-and-publish-components-list.yaml
  .github/workflows/build-and-publish-rule-book.yaml
  .github/workflows/build-and-upload.yaml
  .github/workflows/build-components-list.yaml
  .github/workflows/build-rule-book.yaml
  README.md
  make_printable.sh
Labels: enhancement

#165 Mention >3p game in intro
  sections/introduction.tex
  translations/introduction.tex/introduction.tex.pot
  translations/introduction.tex/pl.po
Labels: changes text

#183 Treasure die
  sections/all_map_locations.tex
  sections/introduction.tex
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/pl.po
  translations/heroes.tex/es.po
  translations/heroes.tex/heroes.tex.pot
  translations/heroes.tex/pl.po
  translations/introduction.tex/es.po
  translations/introduction.tex/introduction.tex.pot
  translations/introduction.tex/pl.po
  translations/units.tex/es.po
  translations/units.tex/pl.po
  translations/units.tex/units.tex.pot
Labels: changes text

#169 Mention when AI cards expire
  sections/ai_heroes.tex
  translations/ai_heroes.tex/ai_heroes.tex.pot
  translations/ai_heroes.tex/pl.po
Labels: changes text

#186 Adjust metadata and printable to all languages
  .github/insert_printable_hyperlinks.py
  .github/qr-codes-pl.tex
  .github/workflows/build-and-publish-rule-book.yaml
  README.md
  main_en.tex
  main_es.tex
  main_pl.tex
  make_printable.sh
  metadata.tex
  sections/credits.tex
  translations/ai_heroes.tex/pl.po
  translations/credits.tex/credits.tex.pot
  translations/credits.tex/es.po
  translations/credits.tex/pl.po
  translations/index.tex/pl.po
  translations/introduction.tex/pl.po
Labels: enhancement

#189 [PL] Fix difficulty typos
  translations/ai_heroes.tex/pl.po
Labels: 🇵🇱 Polish

#182 [ES] Main, Introduction, Credits
  .github/workflows/build-and-publish-rule-book.yaml
  README.md
  main_es.tex
  translations/assets/es/cover_subtitle.png
  translations/credits.tex/es.po
  translations/introduction.tex/es.po
  translations/setup.tex/es.po
  translations/title_page.tex/es.po
Labels: 🇪🇸 Spanish

#190 Update Spanish translations
  translations/ai_heroes.tex/es.po
  translations/credits.tex/es.po
  translations/introduction.tex/es.po
Labels: 🇪🇸 Spanish

#191 Add missing MPs to setup page
  .github/CODEOWNERS
  assets/images/setup.png
  sections/setup.tex
  translations/setup.tex/es.po
  translations/setup.tex/pl.po
  translations/setup.tex/setup.tex.pot
Labels: bug, changes text

#187 Make Dice index entry
  assets/images/attack_die.png
  assets/images/resource_die.png
  assets/images/treasure_die.png
  sections/all_map_locations.tex
  sections/combat.tex
  sections/resources.tex
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/pl.po
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/es.po
  translations/combat.tex/pl.po
  translations/resources.tex/es.po
  translations/resources.tex/pl.po
  translations/resources.tex/resources.tex.pot
Labels: changes text

#203 [ES] Scenario End
  translations/scenario_end.tex/es.po
Labels: 🇪🇸 Spanish

#205 [PL] Polish corrections
  build.sh
  translations/credits.tex/pl.po
  translations/game_modes.tex/pl.po
  translations/round_structure.tex/pl.po
Labels: 🇵🇱 Polish

#196 [ES] Game Modes
  translations/game_modes.tex/es.po
Labels: 🇪🇸 Spanish

#212 Fix card header count errors
  components_lists/battlefield.tex
  components_lists/tower.tex
Labels: bug

#150 [PL] Town translation
  .gitignore
  translations/town.tex/pl.po
Labels: 🇵🇱 Polish

#200 Add rule clarification about AI cards
  sections/ai_heroes.tex
  translations/ai_heroes.tex/ai_heroes.tex.pot
  translations/ai_heroes.tex/es.po
  translations/ai_heroes.tex/pl.po
  translations/game_modes.tex/es.po
Labels: changes text

#199 Add notes for the printable build
  .github/workflows/build-and-publish-rule-book.yaml
  assets/art/ballista.png
  assets/art/devil.jpg
  make_printable.sh
  metadata.tex
  po4a.cfg
  sections/difficulty.tex
  sections/notes.tex
  translations/difficulty.tex/difficulty.tex.pot
  translations/difficulty.tex/es.po
  translations/difficulty.tex/pl.po
  translations/notes.tex/es.po
  translations/notes.tex/notes.tex.pot
  translations/notes.tex/pl.po
  translations/town.tex/pl.po
Labels: changes text

#202 [ES] Round Structure
  translations/round_structure.tex/es.po
Labels: 🇪🇸 Spanish

#204 [ES] Player Turns
  translations/credits.tex/es.po
  translations/introduction.tex/es.po
  translations/player_turns.tex/es.po
  translations/scenario_end.tex/es.po
  translations/setup.tex/es.po
Labels: 🇪🇸 Spanish

#217 Fix pl index
  .github/workflows/build-and-publish-rule-book.yaml
  clean.sh
  make_printable.sh
  metadata.tex
Labels: bug, 🇵🇱 Polish, changes text

#222 [ES] Notes
  translations/notes.tex/es.po
Labels: 🇪🇸 Spanish

#211 Scenario end: solo campaign
  assets/art/medusa.png
  sections/deckbuilding.tex
  sections/game_modes.tex
  sections/scenario_end.tex
  translations/deckbuilding.tex/deckbuilding.tex.pot
  translations/deckbuilding.tex/es.po
  translations/deckbuilding.tex/pl.po
  translations/difficulty.tex/difficulty.tex.pot
  translations/difficulty.tex/es.po
  translations/difficulty.tex/pl.po
  translations/game_modes.tex/es.po
  translations/game_modes.tex/game_modes.tex.pot
  translations/game_modes.tex/pl.po
  translations/scenario_end.tex/es.po
  translations/scenario_end.tex/pl.po
  translations/scenario_end.tex/scenario_end.tex.pot
Labels: changes text

#218 [FR] Translation introduction
  translations/introduction.tex/fr.po
Labels: 🇫🇷 French

#229 [ES] Deck Building
  translations/deckbuilding.tex/es.po
  translations/round_structure.tex/es.po
Labels: 🇪🇸 Spanish

#231 Update README.md
  README.md
Labels: 🇪🇸 Spanish

#233 [ES] Town
  translations/town.tex/es.po
Labels: 🇪🇸 Spanish

#179 [PL] Other rules.
  translations/assets/pl/field_difficulty.png
  translations/assets/pl/trade_table.png
  translations/back_cover.tex/pl.po
  translations/difficulty.tex/pl.po
  translations/other_rules.tex/pl.po
Labels: 🇵🇱 Polish

#239 Fix hyphens and font size in Resources section
  sections/resources.tex
  translations/expansion_content.tex/pl.po
  translations/resources.tex/es.po
  translations/resources.tex/fr.po
  translations/resources.tex/pl.po
  translations/resources.tex/resources.tex.pot
Labels: bug, changes text

#230 [ES] Resources
  translations/resources.tex/es.po
Labels: 🇪🇸 Spanish

#238 [PL] AI Heroes update
  translations/ai_heroes.tex/pl.po
Labels: 🇵🇱 Polish

#254 [ES] AI Heroes
  translations/ai_heroes.tex/es.po
Labels: 🇪🇸 Spanish

#256 [ES] Trading
  translations/trading.tex/es.po
Labels: 🇪🇸 Spanish

#255 [ES] Dificulty
  translations/difficulty.tex/es.po
Labels: 🇪🇸 Spanish

#240 [ES] Units
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#258 [FR] Player turns
  translations/player_turns.tex/fr.po
Labels: 🇫🇷 French

#225 [FR] Setup
  translations/setup.tex/fr.po
Labels: 🇫🇷 French

#220 [FR] French Translation game modes
  translations/game_modes.tex/fr.po
Labels: 🇫🇷 French

#242 [RU] adding RU support + introduction page
  .github/CODEOWNERS
  .github/qr-codes-ru.tex
  .github/workflows/build-and-publish-rule-book.yaml
  README.md
  clean.sh
  main_ru.tex
  metadata.tex
  po4a.cfg
  translations/ai_heroes.tex/ru.po
  translations/all_map_locations.tex/ru.po
  translations/back_cover.tex/ru.po
  translations/combat.tex/ru.po
  translations/credits.tex/ru.po
  translations/deckbuilding.tex/ru.po
  translations/difficulty.tex/ru.po
  translations/expansion_content.tex/ru.po
  translations/game_modes.tex/ru.po
  translations/heroes.tex/ru.po
  translations/index.tex/ru.po
  translations/introduction.tex/ru.po
  translations/map_elements.tex/ru.po
  translations/notes.tex/ru.po
  translations/other_rules.tex/ru.po
  translations/player_turns.tex/ru.po
  translations/resources.tex/ru.po
  translations/round_structure.tex/ru.po
  translations/scenario_end.tex/ru.po
  translations/setup.tex/ru.po
  translations/title_page.tex/ru.po
  translations/town.tex/ru.po
  translations/trading.tex/ru.po
  translations/units.tex/ru.po
Labels: 🇷🇺 Russian

#257 Clarify rules of defending, based on Alex K's answer
  sections/combat.tex
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/es.po
  translations/combat.tex/fr.po
  translations/combat.tex/pl.po
  translations/combat.tex/ru.po
  translations/deckbuilding.tex/ru.po
  translations/map_elements.tex/ru.po
  translations/resources.tex/ru.po
  translations/units.tex/ru.po
Labels: changes text

#241 Update the text followed today's question in discord
  sections/heroes.tex
  translations/heroes.tex/es.po
  translations/heroes.tex/fr.po
  translations/heroes.tex/heroes.tex.pot
  translations/heroes.tex/pl.po
  translations/heroes.tex/ru.po
Labels: changes text

#260 [FR] heroes section
  translations/heroes.tex/fr.po
Labels: 🇫🇷 French

#271 [FR] resources
  translations/resources.tex/fr.po
Labels: 🇫🇷 French

#270 [FR] town
  translations/town.tex/fr.po
Labels: 🇫🇷 French

#280 [ES] Map Elements
  translations/map_elements.tex/es.po
Labels: 🇪🇸 Spanish

#268 [RU] title page + screenshots script
  README.md
  pdf2image.sh
  translations/assets/ru/cover_subtitle.png
  translations/title_page.tex/ru.po
Labels: 🇷🇺 Russian

#267 [RU] Round Structure
  translations/round_structure.tex/ru.po
Labels: 🇷🇺 Russian

#269 [FR] map elements
  translations/map_elements.tex/fr.po
Labels: 🇫🇷 French

#262 [FR] Deckbuilding
  translations/deckbuilding.tex/fr.po
Labels: 🇫🇷 French

#210 [PL] Scenario End
  translations/scenario_end.tex/pl.po
Labels: 🇵🇱 Polish

#265 [PL] Units
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#266 Switch to TTF fonts for Russian build
  .github/workflows/build-and-publish-rule-book.yaml
  build.sh
  main_ru.tex
  metadata.tex
Labels: changes text

#276 Address developer comment
  sections/all_map_locations.tex
  sections/trading.tex
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/fr.po
  translations/all_map_locations.tex/pl.po
  translations/all_map_locations.tex/ru.po
  translations/trading.tex/es.po
  translations/trading.tex/fr.po
  translations/trading.tex/pl.po
  translations/trading.tex/ru.po
  translations/trading.tex/trading.tex.pot
Labels: changes text

#288 [FR] units
  translations/units.tex/fr.po
Labels: 🇫🇷 French

#287 [ES] All Map Locations
  translations/all_map_locations.tex/es.po
Labels: 🇪🇸 Spanish

#173 [PL] Combat translation
  translations/combat.tex/pl.po
Labels: 🇵🇱 Polish

#272 Latex table to mimic table from original book
  assets/glyphs/arrow_right_gray.svg
  assets/glyphs/bronze-table.svg
  assets/glyphs/damage-table.svg
  assets/layout/table-background.jpg
  assets/tables/field_difficulty.png
  assets/tables/optional_rules.png
  assets/tables/trade_table.png
  assets/tables/unit_list.png
  metadata.tex
  sections/back_cover.tex
  sections/difficulty.tex
  sections/introduction.tex
  sections/trading.tex
  sections/units.tex
  translations/all_map_locations.tex/pl.po
  translations/back_cover.tex/back_cover.tex.pot
  translations/back_cover.tex/es.po
  translations/back_cover.tex/fr.po
  translations/back_cover.tex/pl.po
  translations/back_cover.tex/ru.po
  translations/difficulty.tex/difficulty.tex.pot
  translations/difficulty.tex/es.po
  translations/difficulty.tex/fr.po
  translations/difficulty.tex/pl.po
  translations/difficulty.tex/ru.po
  translations/introduction.tex/es.po
  translations/introduction.tex/fr.po
  translations/introduction.tex/introduction.tex.pot
  translations/introduction.tex/pl.po
  translations/introduction.tex/ru.po
  translations/trading.tex/es.po
  translations/trading.tex/fr.po
  translations/trading.tex/pl.po
  translations/trading.tex/ru.po
  translations/trading.tex/trading.tex.pot
  translations/units.tex/es.po
  translations/units.tex/fr.po
  translations/units.tex/pl.po
  translations/units.tex/ru.po
  translations/units.tex/units.tex.pot
Labels: changes text

#264 [ES] Expansion Content
  translations/expansion_content.tex/es.po
Labels: 🇪🇸 Spanish

#310 [PL] Use Polish assets
  main_pl.tex
  translations/assets/pl/arrow_tower.png
  translations/assets/pl/cover_subtitle.png
  translations/assets/pl/empowered_statistic.png
  translations/assets/pl/event.png
  translations/assets/pl/specialty.png
  translations/assets/pl/statistic.png
  translations/assets/pl/war_machine.png
  translations/combat.tex/pl.po
  translations/deckbuilding.tex/pl.po
  translations/expansion_content.tex/pl.po
  translations/scenario_end.tex/pl.po
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#263 [RU] game modes + setup
  translations/game_modes.tex/ru.po
  translations/introduction.tex/ru.po
  translations/setup.tex/ru.po
Labels: 🇷🇺 Russian

#279 [RU] player turns
  translations/player_turns.tex/ru.po
Labels: 🇷🇺 Russian

#283 [RU] heroes
  translations/heroes.tex/ru.po
Labels: 🇷🇺 Russian

#307 [FR] option to avoid french typography of lists Update main_fr.tex
  main_fr.tex
  translations/deckbuilding.tex/fr.po
  translations/introduction.tex/fr.po
  translations/map_elements.tex/fr.po
  translations/player_turns.tex/fr.po
  translations/round_structure.tex/fr.po
  translations/setup.tex/fr.po
Labels: 🇫🇷 French

#297 [FR] expansion content
  translations/expansion_content.tex/fr.po
Labels: 🇫🇷 French

#304 [RU] Use liberation font for headers too
  .github/workflows/build-and-publish-rule-book.yaml
  assets/fonts/Liberation-license.txt
  assets/fonts/LiberationSerif-Bold.ttf
  assets/fonts/LiberationSerif-BoldItalic.ttf
  assets/fonts/LiberationSerif-Italic.ttf
  assets/fonts/LiberationSerif-Regular.ttf
  assets/fonts/versions.txt
  main_ru.tex
Labels: 🇷🇺 Russian

#312 Find fuzzy script
  .github/CODEOWNERS
  README.md
  clean.sh
  find_fuzzy.sh
Labels: enhancement

#292 [FR] ai heroes
  translations/ai_heroes.tex/fr.po
  translations/other_rules.tex/fr.po
Labels: 🇫🇷 French

#293 [FR] trading
  translations/trading.tex/fr.po
Labels: 🇫🇷 French

#299 [FR] difficulty
  translations/difficulty.tex/fr.po
Labels: 🇫🇷 French

#318 [PL] Add Polish graphics
  translations/assets/pl/ability.png
  translations/assets/pl/artifact.png
  translations/assets/pl/hero.png
  translations/assets/pl/spell_example.png
  translations/assets/pl/units.png
  translations/credits.tex/pl.po
Labels: 🇵🇱 Polish

#313 [ES] Combat Spanish
  translations/combat.tex/es.po
Labels: 🇪🇸 Spanish

#329 [PL] Resources
  translations/resources.tex/pl.po
Labels: 🇵🇱 Polish

#301 [RU] resources
  README.md
  translations/resources.tex/ru.po
Labels: 🇷🇺 Russian

#303 [RU] town
  translations/town.tex/ru.po
Labels: 🇷🇺 Russian

#321 [RU] map elements
  translations/map_elements.tex/ru.po
Labels: 🇷🇺 Russian

#335 [PL] Fix combat layout
  translations/combat.tex/pl.po
Labels: 🇵🇱 Polish
