Repository Heegu-sama/Homm3BG, pull requests merged in 2024-06, with the labels that each got.

#551 [ES] Fix Components
  translations/components.tex/es.po
Labels: 🇪🇸 Spanish

#549 [FR] fix fuzzy back cover
  translations/back_cover.tex/fr.po
Labels: 🇫🇷 French

#563 [CS] index + introduction
  README.md
  translations/index.tex/cs.po
  translations/introduction.tex/cs.po
Labels: 🇨🇿 Czech

#564 [CS] game modes
  README.md
  translations/ai_rules.tex/cs.po
  translations/game_modes.tex/cs.po
  translations/scenario_end.tex/cs.po
Labels: 🇨🇿 Czech

#565 [CS] components
  README.md
  translations/components.tex/cs.po
Labels: 🇨🇿 Czech

#566 [CS] setup
  translations/setup.tex/cs.po
Labels: 🇨🇿 Czech

#568 [PL] Update combat and deckbuilding
  translations/combat.tex/pl.po
  translations/deckbuilding.tex/pl.po
Labels: 🇵🇱 Polish

#569 [CS] round structure
  .github/workflows/build-and-publish-rule-book.yaml
  main_cs.tex
  tools/build.sh
  translations/round_structure.tex/cs.po
Labels: 🇨🇿 Czech

#576 [CS] map elements
  translations/map_elements.tex/cs.po
Labels: 🇨🇿 Czech

#573 [CS] credits + notes + back cover
  translations/back_cover.tex/cs.po
  translations/credits.tex/cs.po
  translations/notes.tex/cs.po
Labels: 🇨🇿 Czech

#571 [CS] heroes
  translations/heroes.tex/cs.po
  translations/setup.tex/cs.po
Labels: 🇨🇿 Czech

#572 [CS] deckbuilding
  translations/deckbuilding.tex/cs.po
Labels: 🇨🇿 Czech

#574 [CS] resources
  translations/resources.tex/cs.po
Labels: 🇨🇿 Czech

#575 [CS] town
  translations/town.tex/cs.po
Labels: 🇨🇿 Czech

#578 [CS] Updating indexes
  translations/game_modes.tex/cs.po
  translations/round_structure.tex/cs.po
  translations/setup.tex/cs.po
Labels: 🇨🇿 Czech

#570 [CS] player turns
  README.md
  translations/components.tex/cs.po
  translations/player_turns.tex/cs.po
  translations/setup.tex/cs.po
Labels: 🇨🇿 Czech

#577 [CS] units
  translations/units.tex/cs.po
Labels: 🇨🇿 Czech

#583 [CS] ai rules
  translations/ai_rules.tex/cs.po
  translations/resources.tex/cs.po
Labels: 🇨🇿 Czech

#585 [CS] trading
  translations/trading.tex/cs.po
Labels: 🇨🇿 Czech

#586 [CS] scenario end
  translations/scenario_end.tex/cs.po
Labels: 🇨🇿 Czech

#587 [CS] expansion content
  translations/deckbuilding.tex/cs.po
  translations/expansion_content.tex/cs.po
Labels: 🇨🇿 Czech

#584 [CS] difficulty
  translations/difficulty.tex/cs.po
Labels: 🇨🇿 Czech

#588 [CS] all map locations + final polishing
  README.md
  translations/all_map_locations.tex/cs.po
  translations/combat.tex/cs.po
  translations/credits.tex/cs.po
  translations/expansion_content.tex/cs.po
  translations/map_elements.tex/cs.po
  translations/resources.tex/cs.po
  translations/units.tex/cs.po
Labels: 🇨🇿 Czech

#591 [ES] fuzzy fix
  translations/back_cover.tex/es.po
  translations/combat.tex/es.po
  translations/deckbuilding.tex/es.po
Labels: 🇪🇸 Spanish

#409 Ru/combat
  README.md
  translations/combat.tex/ru.po
Labels: 🇷🇺 Russian

#595 Ru/ai rules
  translations/ai_rules.tex/ru.po
Labels: 🇷🇺 Russian

#598 ru/scenario_end
  translations/scenario_end.tex/ru.po
Labels: 🇷🇺 Russian

#616 [RU] difficulty
  translations/difficulty.tex/ru.po
Labels: 🇷🇺 Russian

#626 [RU] last pasges
  translations/back_cover.tex/ru.po
  translations/index.tex/ru.po
  translations/notes.tex/ru.po
Labels: 🇷🇺 Russian
