Repository Heegu-sama/Homm3BG, pull requests merged in 2024-05, with the labels that each got.

#337 Strip text of AI card
  assets/cards/ai.png
  sections/ai_heroes.tex
  translations/ai_heroes.tex/ai_heroes.tex.pot
  translations/ai_heroes.tex/es.po
  translations/ai_heroes.tex/fr.po
  translations/ai_heroes.tex/pl.po
  translations/ai_heroes.tex/ru.po
Labels: changes text

#340 [ES] Trading Spanish
  translations/trading.tex/es.po
Labels: 🇪🇸 Spanish

#296 Use proper quotes
  metadata.tex
  sections/all_map_locations.tex
  sections/combat.tex
  sections/heroes.tex
  sections/player_turns.tex
  sections/setup.tex
  sections/units.tex
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/fr.po
  translations/all_map_locations.tex/pl.po
  translations/all_map_locations.tex/ru.po
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/es.po
  translations/combat.tex/fr.po
  translations/combat.tex/pl.po
  translations/combat.tex/ru.po
  translations/heroes.tex/es.po
  translations/heroes.tex/fr.po
  translations/heroes.tex/heroes.tex.pot
  translations/heroes.tex/pl.po
  translations/heroes.tex/ru.po
  translations/player_turns.tex/es.po
  translations/player_turns.tex/fr.po
  translations/player_turns.tex/pl.po
  translations/player_turns.tex/player_turns.tex.pot
  translations/player_turns.tex/ru.po
  translations/setup.tex/es.po
  translations/setup.tex/fr.po
  translations/setup.tex/pl.po
  translations/setup.tex/ru.po
  translations/setup.tex/setup.tex.pot
  translations/units.tex/es.po
  translations/units.tex/fr.po
  translations/units.tex/pl.po
  translations/units.tex/ru.po
  translations/units.tex/units.tex.pot
Labels: changes text

#278 Mention name of the tile
  assets/images/fields.png
  sections/map_elements.tex
  translations/map_elements.tex/es.po
  translations/map_elements.tex/fr.po
  translations/map_elements.tex/map_elements.tex.pot
  translations/map_elements.tex/pl.po
  translations/map_elements.tex/ru.po
Labels: changes text

#327 Fix empty page after Units table in printable
  sections/units.tex
  translations/units.tex/es.po
  translations/units.tex/fr.po
  translations/units.tex/pl.po
  translations/units.tex/ru.po
  translations/units.tex/units.tex.pot
Labels: changes text

#343 [ES] Fuzzy Heroes, Map Elements and Game Modes
  translations/game_modes.tex/es.po
  translations/heroes.tex/es.po
  translations/map_elements.tex/es.po
Labels: 🇪🇸 Spanish

#319 [FR] credits, notes and back_cover
  translations/back_cover.tex/fr.po
  translations/credits.tex/fr.po
  translations/index.tex/fr.po
  translations/notes.tex/fr.po
Labels: 🇫🇷 French

#315 [PL] Units, part 2
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#345 Check num of pages
  .github/workflows/build-and-publish-rule-book.yaml
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/fr.po
  translations/combat.tex/es.po
  translations/map_elements.tex/ru.po
Labels: enhancement

#344 [ES] Fuzzy Deck Building Spanish
  translations/deckbuilding.tex/es.po
Labels: 🇪🇸 Spanish

#354 Fix scripts
  build.sh
  clean.sh
  make_printable.sh
Labels: bug

#341 [UA] Ukrainian setup
  .github/CODEOWNERS
  .github/qr-codes-ua.tex
  .github/workflows/build-and-publish-rule-book.yaml
  README.md
  main_ua.tex
  po4a.cfg
  translations/ai_heroes.tex/ua.po
  translations/all_map_locations.tex/ua.po
  translations/assets/ua/cover_subtitle.png
  translations/back_cover.tex/ua.po
  translations/combat.tex/ua.po
  translations/credits.tex/ua.po
  translations/deckbuilding.tex/ua.po
  translations/difficulty.tex/ua.po
  translations/expansion_content.tex/ua.po
  translations/game_modes.tex/ua.po
  translations/heroes.tex/ua.po
  translations/index.tex/ua.po
  translations/introduction.tex/ua.po
  translations/map_elements.tex/ua.po
  translations/notes.tex/ua.po
  translations/player_turns.tex/ua.po
  translations/resources.tex/ua.po
  translations/round_structure.tex/ua.po
  translations/scenario_end.tex/ua.po
  translations/setup.tex/ua.po
  translations/title_page.tex/ua.po
  translations/town.tex/ua.po
  translations/trading.tex/ua.po
  translations/units.tex/ua.po
Labels: 🇺🇦 Ukrainian

#348 Add PL translation for Map Elements
  translations/all_map_locations.tex/es.po
  translations/back_cover.tex/fr.po
  translations/combat.tex/es.po
  translations/deckbuilding.tex/es.po
  translations/game_modes.tex/es.po
  translations/heroes.tex/es.po
  translations/map_elements.tex/es.po
  translations/map_elements.tex/pl.po
  translations/map_elements.tex/ru.po
  translations/trading.tex/es.po
  translations/units.tex/fr.po
Labels: 🇵🇱 Polish

#277 [PL] Deckbuilding
  translations/deckbuilding.tex/pl.po
Labels: 🇵🇱 Polish

#359 [ES] printable bugs
  translations/ai_heroes.tex/es.po
  translations/all_map_locations.tex/es.po
  translations/combat.tex/es.po
  translations/difficulty.tex/es.po
  translations/scenario_end.tex/es.po
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#342 [PL] Fixes
  translations/ai_heroes.tex/pl.po
  translations/all_map_locations.tex/pl.po
  translations/deckbuilding.tex/pl.po
  translations/difficulty.tex/es.po
  translations/player_turns.tex/pl.po
  translations/units.tex/es.po
Labels: 🇵🇱 Polish

#364 Nothing
  .github/workflows/po4a-on-comment.yaml
Labels: enhancement

#362 Remove yellow outline from table stars
  assets/glyphs/bronze-table.svg
  sections/back_cover.tex
  sections/introduction.tex
  sections/units.tex
  translations/back_cover.tex/back_cover.tex.pot
  translations/back_cover.tex/es.po
  translations/back_cover.tex/fr.po
  translations/back_cover.tex/pl.po
  translations/back_cover.tex/ru.po
  translations/back_cover.tex/ua.po
  translations/introduction.tex/es.po
  translations/introduction.tex/fr.po
  translations/introduction.tex/introduction.tex.pot
  translations/introduction.tex/pl.po
  translations/introduction.tex/ru.po
  translations/introduction.tex/ua.po
  translations/units.tex/es.po
  translations/units.tex/fr.po
  translations/units.tex/pl.po
  translations/units.tex/ru.po
  translations/units.tex/ua.po
  translations/units.tex/units.tex.pot
Labels: changes text

#324 Reword Windmill
  sections/all_map_locations.tex
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/fr.po
  translations/all_map_locations.tex/pl.po
  translations/all_map_locations.tex/ru.po
  translations/all_map_locations.tex/ua.po
  translations/credits.tex/credits.tex.pot
  translations/credits.tex/es.po
  translations/credits.tex/fr.po
  translations/credits.tex/pl.po
  translations/credits.tex/ru.po
  translations/credits.tex/ua.po
  translations/expansion_content.tex/es.po
  translations/expansion_content.tex/expansion_content.tex.pot
  translations/expansion_content.tex/fr.po
  translations/expansion_content.tex/pl.po
  translations/expansion_content.tex/ru.po
  translations/expansion_content.tex/ua.po
  translations/game_modes.tex/es.po
  translations/game_modes.tex/fr.po
  translations/game_modes.tex/game_modes.tex.pot
  translations/game_modes.tex/pl.po
  translations/game_modes.tex/ru.po
  translations/game_modes.tex/ua.po
  translations/units.tex/es.po
  translations/units.tex/fr.po
  translations/units.tex/pl.po
  translations/units.tex/ru.po
  translations/units.tex/ua.po
  translations/units.tex/units.tex.pot
Labels: changes text

#367 [PL] Translate optional rules table
  translations/difficulty.tex/pl.po
Labels: 🇵🇱 Polish

#375 [FR] revision for difficulty, notes and trade
  translations/difficulty.tex/difficulty.tex.pot
  translations/difficulty.tex/es.po
  translations/difficulty.tex/fr.po
  translations/difficulty.tex/pl.po
  translations/difficulty.tex/ru.po
  translations/difficulty.tex/ua.po
  translations/trading.tex/fr.po
Labels: 🇫🇷 French

#374 [FR] revision for deckbuilding, resources, town
  translations/deckbuilding.tex/fr.po
  translations/resources.tex/fr.po
  translations/town.tex/fr.po
Labels: 🇫🇷 French

#373 [FR] revision for ai_heroes, all_map_locations, expansion
  translations/ai_heroes.tex/fr.po
  translations/all_map_locations.tex/fr.po
  translations/expansion_content.tex/fr.po
Labels: 🇫🇷 French

#376 [FR] Revision for intro
  .github/workflows/build-and-publish-rule-book.yaml
  translations/introduction.tex/fr.po
Labels: 🇫🇷 French

#371 [ES] Back Cover and Difficulty Bug
  translations/back_cover.tex/es.po
  translations/difficulty.tex/es.po
Labels: 🇪🇸 Spanish

#372 [FR] revision for map_element, units, combat
  translations/combat.tex/fr.po
  translations/map_elements.tex/fr.po
  translations/units.tex/fr.po
Labels: 🇫🇷 French

#370 [FR] revision for setup, player_turns, heroes
  translations/heroes.tex/fr.po
  translations/player_turns.tex/fr.po
  translations/setup.tex/fr.po
Labels: 🇫🇷 French

#381 [PL] Add assets
  translations/assets/pl/alamar_empowering_magic_arrow.png
  translations/assets/pl/fireball_over_magic_arrow.png
  translations/assets/pl/sandro_empowering_lightning_bolt.png
  translations/assets/pl/sandro_empowering_town_portal.png
  translations/assets/pl/skeletons_flipped.png
  translations/assets/pl/zombies_attack_griffins.png
  translations/combat.tex/pl.po
  translations/deckbuilding.tex/pl.po
  translations/map_elements.tex/pl.po
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#384 [PL] Fixes and typos
  translations/all_map_locations.tex/pl.po
  translations/introduction.tex/pl.po
  translations/setup.tex/pl.po
  translations/trading.tex/pl.po
Labels: 🇵🇱 Polish

#386 [ES] Fuzzy Bugs
  translations/ai_rules.tex/es.po
  translations/all_map_locations.tex/es.po
  translations/deckbuilding.tex/es.po
  translations/introduction.tex/es.po
Labels: 🇪🇸 Spanish

#352 [PL] Heroes
  translations/heroes.tex/pl.po
Labels: 🇵🇱 Polish

#356 Introduction UA
  translations/introduction.tex/ua.po
Labels: 🇺🇦 Ukrainian

#355 Game modes UA
  README.md
  translations/game_modes.tex/ua.po
Labels: 🇺🇦 Ukrainian

#326 Clarify exiting blocked fields
  sections/map_elements.tex
  translations/map_elements.tex/es.po
  translations/map_elements.tex/fr.po
  translations/map_elements.tex/map_elements.tex.pot
  translations/map_elements.tex/pl.po
  translations/map_elements.tex/ru.po
  translations/map_elements.tex/ua.po
Labels: changes text

#357 Setup UA
  translations/setup.tex/ua.po
Labels: 🇺🇦 Ukrainian

#400 [FR] Update for exiting blocked fields
  translations/map_elements.tex/fr.po
Labels: 🇫🇷 French

#338 [RU] units
  translations/units.tex/ru.po
Labels: 🇷🇺 Russian

#402 [PL] Fix wording and commas
  .github/CODEOWNERS
  translations/ai_rules.tex/pl.po
  translations/all_map_locations.tex/pl.po
  translations/combat.tex/pl.po
  translations/difficulty.tex/pl.po
  translations/heroes.tex/pl.po
  translations/player_turns.tex/pl.po
  translations/setup.tex/pl.po
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#404 [DE] German translation
  .github/CODEOWNERS
  .github/qr-codes-de.tex
  .github/workflows/build-and-publish-rule-book.yaml
  README.md
  main_de.tex
  po4a.cfg
  tools/clean.sh
  translations/ai_rules.tex/de.po
  translations/all_map_locations.tex/de.po
  translations/assets/de/cover_subtitle.png
  translations/back_cover.tex/de.po
  translations/combat.tex/de.po
  translations/credits.tex/de.po
  translations/deckbuilding.tex/de.po
  translations/difficulty.tex/de.po
  translations/expansion_content.tex/de.po
  translations/game_modes.tex/de.po
  translations/heroes.tex/de.po
  translations/index.tex/de.po
  translations/introduction.tex/de.po
  translations/map_elements.tex/de.po
  translations/notes.tex/de.po
  translations/player_turns.tex/de.po
  translations/resources.tex/de.po
  translations/round_structure.tex/de.po
  translations/scenario_end.tex/de.po
  translations/setup.tex/de.po
  translations/title_page.tex/de.po
  translations/town.tex/de.po
  translations/trading.tex/de.po
  translations/units.tex/de.po
Labels: 🇩🇪 German

#395 [UA] Round Structure
  translations/round_structure.tex/ua.po
Labels: 🇺🇦 Ukrainian

#408 [ES] Map Elements
  translations/map_elements.tex/es.po
Labels: 🇪🇸 Spanish

#397 [UA] Heroes
  translations/heroes.tex/ua.po
Labels: 🇺🇦 Ukrainian

#396 [UA] Player Turns
  translations/player_turns.tex/ua.po
Labels: 🇺🇦 Ukrainian

#398 [UA] Deck-building
  translations/deckbuilding.tex/ua.po
Labels: 🇺🇦 Ukrainian

#411 [UA] Resources
  translations/resources.tex/ua.po
Labels: 🇺🇦 Ukrainian

#403 [RU] map elements updates
  translations/map_elements.tex/ru.po
Labels: 🇷🇺 Russian

#394 [UA] Combat
  translations/combat.tex/ua.po
Labels: 🇺🇦 Ukrainian

#416 Make setup image visible with enumeration
  metadata.tex
  sections/setup.tex
  translations/setup.tex/de.po
  translations/setup.tex/es.po
  translations/setup.tex/fr.po
  translations/setup.tex/pl.po
  translations/setup.tex/ru.po
  translations/setup.tex/setup.tex.pot
  translations/setup.tex/ua.po
Labels: enhancement, changes text

#415 Make unvisited bold
  sections/combat.tex
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/de.po
  translations/combat.tex/es.po
  translations/combat.tex/fr.po
  translations/combat.tex/pl.po
  translations/combat.tex/ru.po
  translations/combat.tex/ua.po
Labels: changes text

#420 [PL] Various fixes
  translations/assets/pl/spell_example.png
  translations/combat.tex/pl.po
  translations/map_elements.tex/pl.po
Labels: bug, 🇵🇱 Polish

#422 [UA]Combat update
  translations/combat.tex/ua.po
Labels: 🇺🇦 Ukrainian

#425 [UA] Units
  translations/units.tex/ua.po
Labels: 🇺🇦 Ukrainian

#428 [UA] AI Rules
  translations/ai_rules.tex/ua.po
Labels: 🇺🇦 Ukrainian

#430 [UA] Difficulty
  translations/difficulty.tex/ua.po
Labels: 🇺🇦 Ukrainian

#412 [UA] Town
  translations/town.tex/ua.po
Labels: 🇺🇦 Ukrainian

#424 [PL] Fix note box
  translations/deckbuilding.tex/pl.po
Labels: bug, 🇵🇱 Polish

#432 [PL] Components
  README.md
  sections/components.tex
  translations/combat.tex/pl.po
  translations/components.tex/components.tex.pot
  translations/components.tex/de.po
  translations/components.tex/es.po
  translations/components.tex/fr.po
  translations/components.tex/pl.po
  translations/components.tex/ru.po
  translations/components.tex/ua.po
  translations/expansion_content.tex/pl.po
Labels: 🇵🇱 Polish, changes text

#433 Prepare for 1.2 release
  main_de.tex
  main_en.tex
  main_es.tex
  main_fr.tex
  main_pl.tex
  main_ru.tex
  main_ua.tex
  sections/credits.tex
  translations/credits.tex/credits.tex.pot
  translations/credits.tex/de.po
  translations/credits.tex/es.po
  translations/credits.tex/fr.po
  translations/credits.tex/pl.po
  translations/credits.tex/ru.po
  translations/credits.tex/ua.po
Labels: changes text

#434 [UA] Trading
  translations/trading.tex/ua.po
Labels: 🇺🇦 Ukrainian

#439 [FR] components
  README.md
  translations/all_map_locations.tex/fr.po
  translations/combat.tex/fr.po
  translations/components.tex/fr.po
  translations/deckbuilding.tex/fr.po
  translations/expansion_content.tex/fr.po
  translations/player_turns.tex/fr.po
  translations/round_structure.tex/fr.po
  translations/units.tex/fr.po
Labels: 🇫🇷 French

#413 [UA] Map Elements
  translations/map_elements.tex/ua.po
Labels: 🇺🇦 Ukrainian

#414 [DE] Game Modes
  translations/game_modes.tex/de.po
Labels: 🇩🇪 German

#419 [DE] Setup
  translations/setup.tex/de.po
Labels: 🇩🇪 German

#435 [UA] Scenario End
  translations/scenario_end.tex/ua.po
Labels: 🇺🇦 Ukrainian

#436 [UA] Expansion Content
  translations/expansion_content.tex/ua.po
Labels: 🇺🇦 Ukrainian

#437 [UA] All Map Locations
  translations/all_map_locations.tex/ua.po
Labels: 🇺🇦 Ukrainian

#442 [FR] second global revision
  translations/combat.tex/fr.po
  translations/deckbuilding.tex/fr.po
  translations/difficulty.tex/fr.po
  translations/map_elements.tex/fr.po
  translations/player_turns.tex/fr.po
  translations/scenario_end.tex/fr.po
  translations/town.tex/fr.po
  translations/trading.tex/fr.po
  translations/units.tex/fr.po
Labels: 🇫🇷 French

#444 [RU] Fix several todos in first sections
  translations/game_modes.tex/ru.po
  translations/introduction.tex/ru.po
  translations/setup.tex/ru.po
Labels: 🇷🇺 Russian

#445 [UA] Back Cover
  translations/back_cover.tex/ua.po
Labels: 🇺🇦 Ukrainian

#438 [ES] Components and fuzzy solved
  translations/combat.tex/es.po
  translations/components.tex/es.po
  translations/deckbuilding.tex/es.po
  translations/expansion_content.tex/es.po
  translations/player_turns.tex/es.po
  translations/round_structure.tex/es.po
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#446 [PL] Translate quote
  main_pl.tex
Labels: 🇵🇱 Polish

#447 [RU] unfuzzy, decapitalize
  translations/heroes.tex/ru.po
  translations/player_turns.tex/ru.po
  translations/round_structure.tex/ru.po
  translations/setup.tex/ru.po
Labels: 🇷🇺 Russian

#448 Fix printable workflow build
  .github/workflows/build-and-publish-rule-book.yaml
  tools/make_printable.sh
Labels: bug

#440 [UA] Components
  README.md
  main_ua.tex
  translations/combat.tex/ua.po
  translations/components.tex/ua.po
  translations/player_turns.tex/ua.po
  translations/round_structure.tex/ua.po
  translations/units.tex/ua.po
Labels: 🇺🇦 Ukrainian

#450 Use ghostscript to compress workflow PDFs
  .github/workflows/build-and-publish-rule-book.yaml
  README.md
  tools/optimize.sh
Labels: enhancement

#449 [UA] Credits
  translations/credits.tex/ua.po
Labels: 🇺🇦 Ukrainian

#472 Clarify the order in which AI units attack
  sections/ai_rules.tex
  translations/ai_rules.tex/ai_rules.tex.pot
  translations/ai_rules.tex/de.po
  translations/ai_rules.tex/es.po
  translations/ai_rules.tex/fr.po
  translations/ai_rules.tex/pl.po
  translations/ai_rules.tex/ru.po
  translations/ai_rules.tex/ua.po
Labels: changes text

#471 Clarify quick combat
  sections/combat.tex
  translations/combat.tex/combat.tex.pot
  translations/combat.tex/de.po
  translations/combat.tex/es.po
  translations/combat.tex/fr.po
  translations/combat.tex/pl.po
  translations/combat.tex/ru.po
  translations/combat.tex/ua.po
Labels: changes text

#481 [FR] ai neutralunits and combat text
  translations/ai_rules.tex/fr.po
  translations/combat.tex/fr.po
Labels: 🇫🇷 French

#485 Format quote properly
  main_de.tex
  main_en.tex
  main_es.tex
  main_fr.tex
  main_pl.tex
  main_ru.tex
  main_ua.tex
  metadata.tex
  sections/quote_page.tex
  translations/quote_page.tex/de.po
  translations/quote_page.tex/es.po
  translations/quote_page.tex/fr.po
  translations/quote_page.tex/pl.po
  translations/quote_page.tex/quote_page.tex.pot
  translations/quote_page.tex/ru.po
  translations/quote_page.tex/ua.po
Labels: bug, 🇫🇷 French, 🇵🇱 Polish, changes text, 🇺🇦 Ukrainian

#491 Update ua.po
  translations/units.tex/ua.po
Labels: 🇺🇦 Ukrainian

#493 [PL] Fix broken hyperlinks + typos
  translations/all_map_locations.tex/pl.po
  translations/combat.tex/pl.po
  translations/deckbuilding.tex/pl.po
  translations/expansion_content.tex/pl.po
  translations/units.tex/pl.po
Labels: 🇵🇱 Polish

#473 [ES] Quote
  main_es.tex
  translations/ai_rules.tex/es.po
  translations/combat.tex/es.po
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#492 [UA] Fix hyperlinks
  translations/combat.tex/ua.po
Labels: 🇺🇦 Ukrainian

#488 [FR] Last typos
  translations/ai_rules.tex/fr.po
  translations/all_map_locations.tex/fr.po
  translations/combat.tex/fr.po
  translations/deckbuilding.tex/fr.po
  translations/difficulty.tex/fr.po
  translations/expansion_content.tex/fr.po
  translations/heroes.tex/fr.po
  translations/map_elements.tex/fr.po
  translations/player_turns.tex/fr.po
  translations/quote_page.tex/fr.po
  translations/round_structure.tex/fr.po
  translations/scenario_end.tex/fr.po
  translations/setup.tex/fr.po
  translations/town.tex/fr.po
  translations/trading.tex/fr.po
  translations/units.tex/fr.po
Labels: 🇫🇷 French

#498 Fix off by 1 page index entries
  .github/workflows/build-and-publish-rule-book.yaml
Labels: bug

#486 [PL] Update AI Rules
  translations/ai_rules.tex/pl.po
Labels: 🇵🇱 Polish

#503 Fix a typo
  translations/map_elements.tex/pl.po
Labels: 🇵🇱 Polish

#504 Remove wrong note box
  sections/deckbuilding.tex
  translations/deckbuilding.tex/de.po
  translations/deckbuilding.tex/deckbuilding.tex.pot
  translations/deckbuilding.tex/es.po
  translations/deckbuilding.tex/fr.po
  translations/deckbuilding.tex/pl.po
  translations/deckbuilding.tex/ru.po
  translations/deckbuilding.tex/ua.po
Labels: bug

#517 [UA] fixes for 1.2
  main_ua.tex
  translations/ai_rules.tex/ua.po
  translations/all_map_locations.tex/ua.po
  translations/combat.tex/ua.po
  translations/deckbuilding.tex/ua.po
  translations/difficulty.tex/ua.po
  translations/expansion_content.tex/ua.po
  translations/heroes.tex/ua.po
  translations/index.tex/ua.po
  translations/player_turns.tex/ua.po
  translations/scenario_end.tex/ua.po
  translations/setup.tex/ua.po
  translations/trading.tex/ua.po
  translations/units.tex/ua.po
Labels: 🇺🇦 Ukrainian

#518 [FR] fix trading
  translations/trading.tex/fr.po
Labels: 🇫🇷 French

#520 [ES] Fuzzy fix
  translations/ai_rules.tex/es.po
  translations/all_map_locations.tex/es.po
  translations/combat.tex/es.po
  translations/deckbuilding.tex/es.po
  translations/heroes.tex/es.po
  translations/player_turns.tex/es.po
  translations/trading.tex/es.po
  translations/units.tex/es.po
Labels: 🇪🇸 Spanish

#521 [ES] Index fix
  translations/combat.tex/es.po
  translations/expansion_content.tex/es.po
Labels: 🇪🇸 Spanish

#523 [FR] Adjusting paralysis token
  translations/components.tex/fr.po
Labels: 🇫🇷 French

#543 [PL] Fix punctuation and layout
  translations/combat.tex/pl.po
  translations/trading.tex/pl.po
Labels: 🇵🇱 Polish

#541 [FR] fix linkable
  translations/back_cover.tex/fr.po
  translations/combat.tex/fr.po
  translations/heroes.tex/fr.po
  translations/player_turns.tex/fr.po
  translations/round_structure.tex/fr.po
  translations/town.tex/fr.po
Labels: 🇫🇷 French

#548 [PL] Fix wrong link
  translations/all_map_locations.tex/pl.po
Labels: 🇵🇱 Polish
