Repository Heegu-sama/Homm3BG, pull requests merged in 2024-11, with the labels that each got.

#739 [HE] translate unit box and fix tables
  translations/difficulty.tex/he.po
  translations/units.tex/he.po
Labels: 🇮🇱 Hebrew

#738 [HE] combat
  translations/combat.tex/he.po
Labels: 🇮🇱 Hebrew

#742 [HE] index
  translations/ai_rules.tex/he.po
  translations/all_map_locations.tex/he.po
  translations/combat.tex/he.po
  translations/deckbuilding.tex/he.po
  translations/difficulty.tex/he.po
  translations/expansion_content.tex/he.po
  translations/game_modes.tex/he.po
  translations/heroes.tex/he.po
  translations/index.tex/he.po
  translations/map_elements.tex/he.po
  translations/notes.tex/he.po
  translations/player_turns.tex/he.po
  translations/resources.tex/he.po
  translations/round_structure.tex/he.po
  translations/scenario_end.tex/he.po
  translations/setup.tex/he.po
  translations/town.tex/he.po
  translations/trading.tex/he.po
  translations/units.tex/he.po
Labels: 🇮🇱 Hebrew

#735 [DE] Translation Difficulty
  translations/difficulty.tex/de.po
Labels: 🇩🇪 German

#741 Make difficulty table margins equal
  sections/difficulty.tex
  translations/difficulty.tex/cs.po
  translations/difficulty.tex/de.po
  translations/difficulty.tex/difficulty.tex.pot
  translations/difficulty.tex/es.po
  translations/difficulty.tex/fr.po
  translations/difficulty.tex/he.po
  translations/difficulty.tex/pl.po
  translations/difficulty.tex/ru.po
  translations/difficulty.tex/ua.po
Labels: bug

#722 [DE] Translation Map-Elements
  translations/map_elements.tex/de.po
Labels: 🇩🇪 German

#734 [DE] Translation Town
  translations/town.tex/de.po
Labels: 🇩🇪 German

#736 [DE] Translation Scenario-ending
  translations/scenario_end.tex/de.po
Labels: 🇩🇪 German

#748 [HE] fixing typoes all over the rulebook
  main_he.tex
  translations/ai_rules.tex/he.po
  translations/all_map_locations.tex/he.po
  translations/combat.tex/he.po
  translations/components.tex/he.po
  translations/deckbuilding.tex/he.po
  translations/difficulty.tex/he.po
  translations/expansion_content.tex/he.po
  translations/game_modes.tex/he.po
  translations/heroes.tex/he.po
  translations/introduction.tex/he.po
  translations/map_elements.tex/he.po
  translations/player_turns.tex/he.po
  translations/resources.tex/he.po
  translations/round_structure.tex/he.po
  translations/scenario_end.tex/he.po
  translations/setup.tex/he.po
  translations/trading.tex/he.po
  translations/units.tex/he.po
Labels: 🇮🇱 Hebrew

#737 [DE] Translation Units
  translations/units.tex/de.po
Labels: 🇩🇪 German

#685 Use roman numerals like on the picture described
  sections/all_map_locations.tex
  sections/heroes.tex
  sections/setup.tex
  translations/all_map_locations.tex/all_map_locations.tex.pot
  translations/all_map_locations.tex/cs.po
  translations/all_map_locations.tex/de.po
  translations/all_map_locations.tex/es.po
  translations/all_map_locations.tex/fr.po
  translations/all_map_locations.tex/he.po
  translations/all_map_locations.tex/pl.po
  translations/all_map_locations.tex/ru.po
  translations/all_map_locations.tex/ua.po
  translations/heroes.tex/cs.po
  translations/heroes.tex/de.po
  translations/heroes.tex/es.po
  translations/heroes.tex/fr.po
  translations/heroes.tex/he.po
  translations/heroes.tex/heroes.tex.pot
  translations/heroes.tex/pl.po
  translations/heroes.tex/ru.po
  translations/heroes.tex/ua.po
  translations/setup.tex/cs.po
  translations/setup.tex/de.po
  translations/setup.tex/es.po
  translations/setup.tex/fr.po
  translations/setup.tex/he.po
  translations/setup.tex/pl.po
  translations/setup.tex/ru.po
  translations/setup.tex/setup.tex.pot
  translations/setup.tex/ua.po
Labels: changes text

#745 Make units table symmetric
  sections/units.tex
  translations/units.tex/cs.po
  translations/units.tex/de.po
  translations/units.tex/es.po
  translations/units.tex/fr.po
  translations/units.tex/he.po
  translations/units.tex/pl.po
  translations/units.tex/ru.po
  translations/units.tex/ua.po
  translations/units.tex/units.tex.pot
Labels: bug

#753 [DE] Update Intro
  translations/introduction.tex/de.po
Labels: 🇩🇪 German

#749 New SP clarification
  sections/deckbuilding.tex
  translations/deckbuilding.tex/cs.po
  translations/deckbuilding.tex/de.po
  translations/deckbuilding.tex/deckbuilding.tex.pot
  translations/deckbuilding.tex/es.po
  translations/deckbuilding.tex/fr.po
  translations/deckbuilding.tex/he.po
  translations/deckbuilding.tex/pl.po
  translations/deckbuilding.tex/ru.po
  translations/deckbuilding.tex/ua.po
Labels: changes text

#747 [RU] fixes
  translations/ai_rules.tex/ru.po
  translations/combat.tex/ru.po
  translations/heroes.tex/ru.po
  translations/player_turns.tex/ru.po
  translations/setup.tex/ru.po
  translations/units.tex/ru.po
Labels: 🇷🇺 Russian

#752 [DE] Update Gamemodes
  translations/game_modes.tex/de.po
Labels: 🇩🇪 German
